jobs:
  - file: ./webapp_build.groovy
  - file: ./helm_webapp.groovy
  - file: ./webapp_commit_check.groovy
  - file: ./webapp_processor_build.groovy
  - file: ./terraform_ci.groovy

credentials:
  system:
    domainCredentials:
      - credentials:
          - githubApp:
              id: "github-app"
              description: "GitHub App"
              appID: ${GH_APP_ID}
              privateKey: |
                ${GH_APP_PRIVATE_KEY}

tool:
  #This tool can't be installed against alpine OS
  nodejs:
    defaultProperties:
      - installSource:
          installers:
            - nodeJSInstaller:
                npmPackagesRefreshHours: 72
    installations:
      - name: "node"
        home: ""
        properties:
          - installSource:
              installers:
                - nodeJSInstaller:
                    id: "22"
                    npmPackagesRefreshHours: 72

unclassified:
  location:
    url: https://jenkins.missionk8s.xyz
