name: Packer Build and Validate

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup

      - name: Run `packer init`
        id: init
        run: "packer init ./packer/packer.pkr.hcl"

      - name: Validate Packer configuration
        run: |
          cd ./packer
          packer validate .

      - name: Build Packer image
        run: |
          cd ./packer
          packer build -var "jenkins_username=${{ secrets.JENKINS_USERNAME }}" -var "jenkins_password=${{ secrets.JENKINS_PASSWORD }}" -var "deployment_env=${{ env.DEPLOYMENT_ENV }}" -var "docker_username=${{ env.DOCKER_USERNAME }}" -var "docker_password=${{ env.DOCKER_PASSWORD }}" -var "github_username=${{ secrets.GH_USERNAME }}" -var "github_access_key=${{ secrets.GH_ACCESS_KEY }}" .
        env:
          JENKINS_USERNAME: ${{ secrets.JENKINS_USERNAME }}
          JENKINS_PASSWORD: ${{ secrets.JENKINS_PASSWORD }}
          DEPLOYMENT_ENV: ${{ env.DEPLOYMENT_ENV }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GH_ACCESS_KEY: ${{ secrets.GH_ACCESS_KEY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
